version: "3.3"
services:
  db:
    image: postgres:12
    container_name: maciej_szok_projects_api_db
    restart: always
    volumes:
      - projects-api-db-data-ms:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'

  backend:
    image: 'maciej-szok-projects-api:${TAG-latest}'
    container_name: maciej_szok_projects_api_backend
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - '3000:3000'
    build:
      context: .
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}
    # Uncommenting platform could help with running on M1 Macs
#    platform: linux/amd64 # Patch for M1 Macs


volumes:
  projects-api-db-data-ms:
